### ISSUE TITLE
Metroid Fusion - Incorrect Frequency

### ISSUE THREAD

**Issue by Ckosmick** [Kermalis/VGMusicStudio#101]
Metroid Fusion's sample frequency is 10512Hz. VGMusicStudio as far as I can tell does not change frequency so the pitches on everything are off because it plays tracks at the more traditional 13379Hz.

**Comment by Kermalis** [comment]
You can change the frequency in the MP2K.yaml file. Each frequency has an ID and so you probably put the wrong one (or I did if it's in there already)

**Comment by Ckosmick** [comment]
Ah okay, I had not touched the YAML before making this ticket. It seems the fix is to change the sample rate from 3 to 2 (Line 310)

**Comment by Ckosmick** [comment]
Oh someone from within our community seems to have made a pull request about both GBAtroids, also containing a music track list. https://github.com/Kermalis/VGMusicStudio/pull/80/commits/2f5af07518510ae2cc49ba0a44cb6f5db141999e

**Comment by Kermalis** [comment]
Oh nice, I might just merge that in if I get time
