### ISSUE TITLE
Add support for the F-Zero series

### ISSUE THREAD

**Issue by AnthonyRyuki** [Kermalis/VGMusicStudio#106]
The F-Zero series on GBA uses the MP2K sound engine, as proven by the fact that GBA Music Riper can extract all music and sounds from the ROMs.

Could you please add support for those games? Thanks a lot.

**Comment by Kermalis** [comment]
Hello, I added them. You can copy the changes from here: https://github.com/Kermalis/VGMusicStudio/commit/4f98708f708cac4870814d2f8da21bc74ef351ff

Or you can wait for the new version, but that won't be done for a long time.

**Comment by AnthonyRyuki** [comment]
Thank you very much.
