### ISSUE TITLE
Final Fantasy Dawn of Souls and Final Fantasy VI Advance cause errors

### ISSUE THREAD

**Issue by AvatarMew** [Kermalis/VGMusicStudio#107]
I see "---------------------------
Error Loading GBA ROM (MP2K)
---------------------------
Error Details:

Error parsing "MP2K.yaml"
Game code "BZ6E_00" is missing.
   at Kermalis.VGMusicStudio.Core.GBA.MP2K.Config..ctor(Byte[] rom)
   at Kermalis.VGMusicStudio.Core.Engine..ctor(EngineType type, Object playerArg)
   at Kermalis.VGMusicStudio.UI.MainForm.OpenMP2K(Object sender, EventArgs e)
---------------------------
OK   
---------------------------
" whenever I try to load either of the above roms.

**Comment by Kermalis** [comment]
Hello, these aren't really errors, I just haven't added them to the config yet. I can check it out later today or tomorrow though

**Comment by AvatarMew** [comment]
Ah, I see.

**Comment by AvatarMew** [comment]
I don't think any of the Final Fantasy games are added.

**Comment by Kermalis** [comment]
I added all of them. Final Fantasy Tactics was already there, but now the rest are too. If you're not using the beta version, you can copy the config file here: https://github.com/Kermalis/VGMusicStudio/blob/e52aac40cfe6f00a958144e930fcec19133060f6/VG%20Music%20Studio%20-%20Core/MP2K.yaml
