### ISSUE TITLE
Error while loading rom (MP2k)

### ISSUE THREAD

**Issue by XKoop7321** [Kermalis/VGMusicStudio#113]
I am trying to rip music from yoshis topsy turvy, I have the rom and whenever I try using any of the gba rom imports I get this:

Error Details:

Error parsing "MP2K.yaml"
Game code "KYGE_00" is missing.
   at Kermalis.VGMusicStudio.Core.GBA.MP2K.Config..ctor(Byte[] rom)
   at Kermalis.VGMusicStudio.Core.Engine..ctor(EngineType type, Object playerArg)
   at Kermalis.VGMusicStudio.UI.MainForm.OpenMP2K(Object sender, EventArgs e)

If someone knows how to fix this please let me know. Thanks

**Comment by Kermalis** [comment]
Hello, this just means I haven't added that game to the config. You can add it yourself if you know how, but I will see if I can add it when I have time

**Comment by XKoop7321** [comment]
I don't know how to so i'll wait, thanks for the answer though!

**Comment by Kermalis** [comment]
I have added it to the beta version, but you can download this config file and use it for any version: https://github.com/Kermalis/VGMusicStudio/blob/9e909504bdf4c5e1be42e802bf20143738df893d/VG%20Music%20Studio%20-%20Core/MP2K.yaml

Let me know if you need help

**Comment by XKoop7321** [comment]
Ok thanks!

**Comment by XKoop7321** [comment]
One little question, how do I find the sf2 export

**Comment by Kermalis** [comment]
That feature isn't added back yet for MP2K. You'd have to download "GBAMusicStudio" from the releases which is an old version. You can just put it in a separate folder with the new config and it should still work fine

**Comment by XKoop7321** [comment]
In the older versions I don't see a MP2k.yaml so where do I put the new file?

**Comment by Kermalis** [comment]
It's called Games.yaml in the old one

**Comment by XKoop7321** [comment]
Oh so do I just delete it and put in the MP2K and then change its name?

**Comment by Kermalis** [comment]
Try this one: [Games.zip](https://github.com/Kermalis/VGMusicStudio/files/11082604/Games.zip)

**Comment by XKoop7321** [comment]
Oh ok let me try it.

**Comment by XKoop7321** [comment]
Its working but now whenever I try to export the sf2 it says "Object reference not set to an instance of an object" or "Attempted to read past the end of the stream"

**Comment by Kermalis** [comment]
Hmm, you need to load a song first. But I tried it just now and I get a different error actually (still doesn't work)
I'm not sure how to help with that honestly. Does it work with other games for you?

**Comment by XKoop7321** [comment]
yeah it does, idk why not yoshi's topsy turvy. Is there anyone else on the team who might be able to help?

**Comment by Kermalis** [comment]
Sadly it's just me. You can join the Discord server though, maybe someone knows of another tool that can rip the data to sf2. Personally I only know of `gbamusriper`, you should try it if you're able to navigate the command prompt

**Comment by XKoop7321** [comment]
I don't have discord but I do have email and a thing called google chat, also whenever I try to open gbamusriper nothing happens.

**Comment by Kermalis** [comment]
Yeah, you need to open it with the command prompt. It needs you to type in commands to use it. So if you just double-click it, it instantly closes since there was no command

I think you should consider making a Discord account to join our server. There are lots of people there who can help you. I help people out in there when I have the time

**Comment by XKoop7321** [comment]
Ok, I didn't know that you need command prompt, I saw a video where a guy just double clicked it, I don't remember which one it was. Also I can't join discord because I am too young sadly, But thanks for the offer and info.

**Comment by XKoop7321** [comment]
Say I need your help again, For the latest VG music studio, can you add kirby and the amazing mirror?

**Comment by Kermalis** [comment]
> Say I need your help again, For the latest VG music studio, can you add kirby and the amazing mirror?

Here: https://github.com/Kermalis/VGMusicStudio/commit/df646b7a77f9c8c461f2d901f1482cf3bbabdc31#diff-cdc9c194b8f8edce4b3097baba5d0f11484293ada86dfe7835128f2b5d9b6349

**Comment by XKoop7321** [comment]
Thanks again!

**Comment by XKoop7321** [comment]
Can I also a a games.yaml version too?

**Comment by Kermalis** [comment]
I won't be able to until next week, but you should be able to add it by looking at topsy turvy or other ones and seeing how it works. They are all similar

**Comment by XKoop7321** [comment]
Ah ok.
