### ISSUE TITLE
Request: Loop wav files twice.

### ISSUE THREAD

**Issue by AvatarMew** [Kermalis/VGMusicStudio#114]
If it's possible please make extracted .wav files play twice instead of playing once.
Currently, the extracted files play once.
![Wave](https://user-images.githubusercontent.com/25403481/226912668-d47a546f-18d7-4e4d-ab0f-0c044eb8920b.png)

**Comment by Kermalis** [comment]
You can change this by editing the GlobalConfig.yaml file
