### ISSUE TITLE
ERROR TRYING TO LOAD SONIC ADVANCE 2 ROM INTO VGM STUDIO 

### ISSUE THREAD

**Issue by HUNTINGTHIEVES** [Kermalis/VGMusicStudio#127]
Error Details:

Error parsing "MP2K.yaml"
Game code "A2NE_00" is missing.
   at Kermalis.VGMusicStudio.Core.GBA.MP2K.Config..ctor(Byte[] rom)
   at Kermalis.VGMusicStudio.Core.Engine..ctor(EngineType type, Object playerArg)
   at Kermalis.VGMusicStudio.UI.MainForm.OpenMP2K(Object sender, EventArgs e)

**Comment by PlatinumLucario** [comment]
This is the same as issue #126.

The reason this error occurs, is because the entry isn't added into MP2K.yaml.

**Comment by HUNTINGTHIEVES** [comment]
So how would I fix that or add the entry into mp2k?

**Comment by Kermalis** [comment]
You can use the config from here, I just added this game https://raw.githubusercontent.com/Kermalis/VGMusicStudio/b0d14fb4aac46b5ac2328e3d635702150f109b48/VG%20Music%20Studio%20-%20Core/MP2K.yaml
