### ISSUE TITLE
Export voicegroup to DLS file?

### ISSUE THREAD

**Issue by YouKnowHer** [Kermalis/VGMusicStudio#22]
The other soundfont format which VGMTrans exports to along with SF2. It's more convenient when importing a song into FL Studio since it just imports in one go and you don't need extra setup. It would be really awesome if you could add it here too.

**Comment by Kermalis** [comment]
DLS is a lot tougher to program with because it doesn't really make much sense, and that's why SF2 is more adopted, but I also do like using DLS with FL studio and already considered implementing it

**Comment by Kermalis** [comment]
DLS is now implemented (for AlphaDream only at this time, but I will be adding other engine exporting soon)
