### ISSUE TITLE
There exists no way to tell the version of a GBA ROM.

### ISSUE THREAD

**Issue by CharxBD** [Kermalis/VGMusicStudio#47]
Not sure if I'm just being dumb since I'm sort of new to this, but every time I try to play a track from the Pokemon Ruby NTSC rom that I have, no matter what song I choose, an error like this would come up.
![image](https://user-images.githubusercontent.com/36720319/58218818-7936f080-7cd6-11e9-9506-85776eae4110.png)

**Comment by Kermalis** [comment]
Hello, you probably have a version that is not Ruby v1.0 (there exists v1.1 and v1.2)
Currently the program is only set to load v1.0 but it is something I can change quickly
