### ISSUE TITLE
Add GBC/GB (GBS), NES (NSF) and SNES (SPC) support

### ISSUE THREAD

**Issue by Shorthorn-Studios** [Kermalis/VGMusicStudio#58]
Add support for the NES, Gameboy, SNES and Gameboy Colo(u)r's sound format

**Comment by Kermalis** [comment]
This is not as easy as it sounds and I would like to add them all. Each engine requires loads of research and time and needs to be emulated as well as possible. I've had some code that works with PSF (for PSX) and it still needs lots of work, not to mention some existing engines also are not fully emulated properly, so it takes lots of time. I will get to these eventually if I can, but for now I will close this.
