### ISSUE TITLE
Access games like WarioWare, inc.?

### ISSUE THREAD

**Issue by tahutoa** [Kermalis/VGMusicStudio#65]
I don't remember much about the idea of accessing its music, but I remember being told that it supposedly used actual legitimate MIDI files instead of Sappy sequences.
The error code I get for it is AZWE_00, if that helps.

_(Also, if there's any way to access the music for games like those made by LEGO for the GBA, that'd be cool; games like Knights' Kingdom, Tale of the Tohunga, and so on have interesting sounds to them, but I believe they're not sequenced, and instead are just compressed audio. If it's not possible then whatever, but it'd be neat.)_

**Comment by Kermalis** [comment]
All of these games have different music engines, so they would require lots of research which takes lots of time. I'm currently working on other things as well
