### ISSUE TITLE
"Error loading Global Config. Could not find file 'C:\WINDOWS\system32\Config.yaml'"

### ISSUE THREAD

**Issue by tahutoa** [Kermalis/VGMusicStudio#66]
I open the program once, use it for however long, then close it. I try to open it a second time later on, and I get this message, causing me to need to delete the program and unzip the whole thing all over again. This has happened twice now.

**Comment by Kermalis** [comment]
Hello, where are you unzipping it to, and how are you running the program?

**Comment by tahutoa** [comment]
I was unzipping it to its own folder. Both times when I went to open it the second time, I would type in some variation on "VG Mus" into the Windows 10 search bar, then click the program when it showed in the results. 

I don't know if I needed to go into the containing folder before opening it or what, but I don't think that's supposed to happen. Honestly I don't know why it would need a config file anyway

**Comment by Kermalis** [comment]
Ah I see, running from the search bar starts the program from system32. I will fix this, since it should use the application directory at all times. In the meantime, either double click the exe manually, or create a shortcut that will start it in its own directory.

**Comment by tahutoa** [comment]
Okay, gotcha

**Comment by Kermalis** [comment]
I just pushed a fix, so you can rebuild the project and it'll allow you to launch it anywhere.
