### ISSUE TITLE
How do I actually open the program, now?

### ISSUE THREAD

**Issue by tahutoa** [Kermalis/VGMusicStudio#68]
The latest version of the .zip doesn't have anything that strikes me as being the executable for the program. There is a file with a .SLN extension, and I suspect that's what it's supposed to be, but I can't open that. Is there a file where I need to change the extension to .exe?

**Comment by Kermalis** [comment]
It sounds like you downloaded the wrong zip, you downloaded the one called "source code" instead of the one above it.

**Comment by tahutoa** [comment]
Oh, okay. WEll, in that case, my original problem was the "Classic NES Series Zelda II" file won't open, saying "FLBE_00" is missing. Is this because it doesn't use any sounds at all other than what's inside the hardware?

**Comment by Kermalis** [comment]
That error means the program doesn't know where the songs are located, I'll check that game and see if I can add it.
