### ISSUE TITLE
Song adds artificial fade-out to .wav export.

### ISSUE THREAD

**Issue by Down200** [Kermalis/VGMusicStudio#85]
Small issue, just wondering if this is intentional or a bug. If it's intentional, could an option be added to disable it? I want to extract a ringtone that is used in a game, and usually the ringtone is a perfect loop, but the fade-out removes that.

**Comment by Kermalis** [comment]
https://github.com/Kermalis/VGMusicStudio/blob/master/VG%20Music%20Studio/Config.yaml#L7

Change `PlaylistFadeOutMilliseconds` to 0 in your Config.yaml, then restart the program
