### ISSUE TITLE
Unable to make music!?

### ISSUE THREAD

**Issue by ViolentVHWeaponzz** [Kermalis/VGMusicStudio#87]
Bruh I literally have no option to make a new music file in the music editor. I can't figure out how to make music with this complex software machinery! D:

**Comment by Kermalis** [comment]
This program is a music player, not a music composer. There are other tools to do those things way better

**Comment by ViolentVHWeaponzz** [comment]
I have been backstabbed, I have been betrayed, and possibly bamboozled.
